name: flutter_persist_state_example
description: Example app demonstrating flutter_persist_state usage
version: 0.0.3+3
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_persist_state:
    path: ../
    # Note: This path dependency is only for development.
    # In production, this would be a published version.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
